name: Build

on:
  push:
    branches: [master, main]
    tags: ['v*']
  pull_request:
    branches: [master, main]

env:
  PROJECT_NAME: PPPOE

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - platform: x86
            msbuild_platform: Win32
          - platform: x64
            msbuild_platform: x64
        configuration: [Release]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: |
          msbuild ${{ env.PROJECT_NAME }}.vcxproj `
            /p:Configuration=${{ matrix.configuration }} `
            /p:Platform=${{ matrix.msbuild_platform }} `
            /m

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-${{ matrix.platform }}
          path: build/${{ matrix.platform }}/${{ matrix.configuration }}/${{ env.PROJECT_NAME }}.exe

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create release
        run: |
          for dir in ${{ env.PROJECT_NAME }}-*; do
            zip -j "${dir}-${{ github.ref_name }}.zip" "${dir}/${{ env.PROJECT_NAME }}.exe"
          done
          gh release create ${{ github.ref_name }} *.zip --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
